Configure /etc/machine-id in initramfs

diff --git a/initramfs-scripts/rpi3-machine-id b/initramfs-scripts/rpi3-machine-id
--- a/initramfs-scripts/rpi3-machine-id
+++ b/initramfs-scripts/rpi3-machine-id
@@ -14,10 +14,10 @@ if test -z "$serial"; then
     exit 0
 fi
 
-if ! printf 'rpi3-%s\n' "$serial" > "$rootmnt/etc/hostname"; then
-    log_warning_msg "Could not write $rootmnt/etc/hostname"
+if ! (set -o pipefail; printf '%s' "$serial" | sha256sum | awk '{ print substr($1, 1, 32) }' > "$rootmnt/etc/machine-id"); then
+    log_warning_msg "Could not write $rootmnt/etc/machine-id"
+    rm -f "$rootmnt/etc/machine-id"
     exit 0
 fi
 
 exit 0
-
